### ISSUE TITLE
Fake Blog Grading

### ISSUE THREAD

**Issue by wesharper** [webfun-sept2017/Rommel_Dumaguin_webfun9-2017#1]
Try experimenting with a select element.
https://github.com/webfun-sept2017/Rommel_Dumaguin_webfun9-2017/blob/0396f66bb98bd6027ae6896f6cae2f4f41e3947b/WebFundamentals/Fake_Blog/Fake-Blog.html#L82-L83

**Comment by rdumaguin** [comment]
Can you please clarify what you mean? I have a select element for "favorite language".

**Comment by wesharper** [comment]
Oops! Sorry, I believe I actually meant checkboxes. To be clear, this assignment is satisfactory, so it's probably not worth it to go back.

**Comment by rdumaguin** [comment]
Oh gotcha. Thanks Wes.
