### ISSUE TITLE
Can I Have The Time - Grading

### ISSUE THREAD

**Issue by wesharper** [webfun-sept2017/Rommel_Dumaguin_webfun9-2017#2]
It looks like those should be "PM", what if you passed PERIOD to period? i.e. period(PERIOD)
https://github.com/webfun-sept2017/Rommel_Dumaguin_webfun9-2017/blob/28ac967a0258ba23799ceea70c3e5154a2a4d629/WebFundamentals/If_You_Don't_Mind_Can_I_Have_the_Time/If_You_Don't_Mind_Can_I_Have_the_Time.html#L25-L34

**Comment by rdumaguin** [comment]
Good points. Fixed. Thanks!

**Comment by wesharper** [comment]
Glad this helped!
